#!/usr/bin/env bash

if [[ ! -d ./llvm/lib ]]; then
  echo "Error: directory ./llvm/lib not found"
  exit 1
fi

LDFLAGS="-L\${SRCDIR}/$(realpath --relative-to="$(pwd)" ./llvm/lib)"
for f in ./llvm/lib/*.a; do
    [[ -e "$f" ]] || continue
    filename=$(basename "$f")       # liba.a
    libname="${filename#lib}"       # a.a
    libname="${libname%.a}"         # a
    LDFLAGS="$LDFLAGS -l$libname"
done

cat > "./llvm_config_static.go" <<EOF
//go:build !byollvm && !llvm14 && !llvm15 && !llvm16 && !llvm17 && !llvm18 && !llvm19 && !llvm20 && !llvm21
// Code generated by gen_cgo_ldflags.sh; DO NOT EDIT.

package llvm
/*
#cgo linux        CPPFLAGS: -I\${SRCDIR}/llvm/include/ -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS
#cgo linux        CXXFLAGS: -std=c++17
#cgo linux        LDFLAGS: -Wl,--start-group -lz -lzstd $LDFLAGS -Wl,--end-group
*/
import "C"

type run_build_sh int

EOF

echo "Generated ./llvm_config_static.go for llvm"
